spring:
  profiles:
    active: default
  datasource:
    url: jdbc:sap://your-hana-host:443?encrypt=true&validateCertificate=false
    # username: Varsh
    # password: 1234
    driver-class-name: com.sap.db.jdbc.Driver

cds:
  datasource:
    auto-config:
      enabled: true
  sql:
    supportedLocales: en